# Generated by Django 2.2.1 on 2019-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('band', models.TextField()),
            ],
        ),
    ]
