# Generated by Django 2.2.1 on 2019-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='location',
            field=models.TextField(default='VFW Post 4100 Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='remarks',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
